# Generated by Django 3.2.3 on 2021-06-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=9)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headless', models.BooleanField(default=True)),
                ('maximized', models.BooleanField(default=True)),
                ('use_proxy', models.BooleanField(default=True)),
                ('refresh_delay', models.IntegerField(default=600)),
                ('max_play', models.IntegerField(default=60)),
                ('min_play', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_plays', models.IntegerField(default=0)),
            ],
        ),
    ]
