# Generated by Django 3.2.5 on 2021-07-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210715_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='title',
            field=models.CharField(blank=True, max_length=1299, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='link',
            field=models.URLField(blank=True, max_length=1299, null=True),
        ),
    ]
