# Generated by Django 3.2.5 on 2021-07-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210715_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Setting', 'verbose_name_plural': 'Settings'},
        ),
        migrations.RemoveField(
            model_name='settings',
            name='max_play',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='min_play',
        ),
        migrations.AddField(
            model_name='items',
            name='max_price',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='min_price',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
