# Generated by Django 3.2.5 on 2021-07-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210715_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='max_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='min_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
