# Generated by Django 3.2.5 on 2021-08-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210715_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='use_proxy',
        ),
        migrations.AddField(
            model_name='items',
            name='bought',
            field=models.BooleanField(default=False),
        ),
    ]
