# Generated by Django 3.2.5 on 2021-08-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210809_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='skip',
            field=models.BooleanField(default=False),
        ),
    ]
