# Generated by Django 3.2.5 on 2021-08-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_items_skip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='skip',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
