# Generated by Django 3.2.5 on 2021-08-20 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.accounts'),
        ),
    ]
