# Generated by Django 3.2.5 on 2021-08-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_items_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='profile',
            field=models.CharField(default='Profile_KK1', max_length=255, null=True),
        ),
    ]
