# Generated by Django 3.2.5 on 2021-08-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_items_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='need_verification',
            field=models.BooleanField(default=False),
        ),
    ]
