# Generated by Django 3.2.5 on 2021-09-02 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_items_is_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='need_verification',
        ),
    ]
