# Generated by Django 3.2.5 on 2021-09-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_items_need_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='security_code',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
