# Generated by Django 3.2.5 on 2021-09-02 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_items_security_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='profile',
        ),
        migrations.AlterField(
            model_name='items',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.accounts'),
        ),
        migrations.AlterField(
            model_name='items',
            name='is_test',
            field=models.BooleanField(default=False, help_text='Enable test only for testing purpose.'),
        ),
    ]
