# Generated by Django 3.2.5 on 2021-09-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210902_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='g_password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
