# Generated by Django 3.2.5 on 2021-09-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_accounts_g_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='profile_prefix',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
