# Generated by Django 3.2.5 on 2021-09-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_items_profile_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='headless',
            field=models.BooleanField(default=False, help_text='Turn on Headless Mode if you want to run bot without browser'),
        ),
        migrations.AlterField(
            model_name='items',
            name='profile_prefix',
            field=models.CharField(default='NEW_ITEM', help_text='Profile Prefix is used for cache storing (Saving account).', max_length=500, null=True),
        ),
    ]
