# Generated by Django 3.2.5 on 2021-09-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20210907_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='headless',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='maximized',
        ),
        migrations.AlterField(
            model_name='settings',
            name='headless',
            field=models.BooleanField(default=False),
        ),
    ]
