# Generated by Django 3.2.5 on 2021-09-08 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210908_0129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='profile_prefix',
            new_name='profile_suffix',
        ),
    ]
