# Generated by Django 3.2.5 on 2021-09-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_profile_prefix_items_profile_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='zip_code',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='profile_suffix',
            field=models.CharField(default='NEW_ITEM', help_text='Profile suffix is used for cache storing (Saving account).', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='skip',
            field=models.BooleanField(default=False, help_text='Enable `Skip` if you think login process is not required to do again and again.', null=True),
        ),
    ]
