# Generated by Django 3.2.5 on 2021-09-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20210908_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ending', models.CharField(max_length=4, null=True)),
                ('security_code', models.CharField(max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'Cards Info',
                'verbose_name_plural': 'Cards Info',
            },
        ),
        migrations.RemoveField(
            model_name='items',
            name='security_code',
        ),
    ]
