# Generated by Django 3.2.5 on 2021-11-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20210908_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='force_signin',
            field=models.BooleanField(default=False, help_text='Enable this if you wanna force sign in in to the bot.', null=True),
        ),
    ]
